# File: k8s/backend-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend
    spec:
      containers:
        - name: chatapp-backend
          image: joelchandanshiv/chatapp-backend:latest
          ports:
          - containerPort: 5001
          env:
          - name: NODE_ENV
            value: "production"
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongoadmin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
          - name: MONGODB_URI
            value: "mongodb://mongoadmin:password@mongodb:27017/chatApp?authSource=admin&retryWrites=true&w=majority"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: chat-app-secrets
                key: jwt
          - name: PORT
            value: "5001"

